config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index"
  get "play/:id", to: "play#index", as: 'play'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/act.rb
require_relative './scene'

class Act
  attr_accessor :document, :title, :scenes

  def initialize(document)
    @document = document
    load_title
    load_scenes
  end

  def load_title
    @title = document.css('TITLE').map(&:content)[0]
  end

  def load_scenes
    @scenes = document.css('SCENE').map do |scene_document|
      Scene.new scene_document
    end
  end

  def total_lines
    lines = 0
    scenes.each do |scene|
     scene.speeches.each do |speech|
        lines += speech.lines.size
      end
    end
    return lines
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/play.rb
require 'nokogiri'
require 'open-uri'
require 'set'
require_relative './act'

class Play

  attr_accessor :document, :title, :characters, :acts

  def initialize(source)
    @source = source
    @document = source.source
    load_title
    load_characters
    load_acts
  end

  def lines_by_character(character)
    @lines = 0
    acts.each do |act|
      act.scenes.each do |scene|
        scene.speeches.each do |speech|
          if speech.speaker == character
            @lines += speech.lines.size
          end
        end
      end
    end
    return @lines
  end

  def words_by_character name
    words = Hash.new

    acts.each do |act|
      act.scenes.each do |scene|
        scene.speeches.each do |speech|
          if speech.speaker == name
            speech.lines.map do |line|
              line.split.each do |word|
                word = word.downcase
                if words.has_key?(word)
                  words[word] = words[word] + 1
                else
                  words[word] = 1
                end
              end
            end
          end
        end
      end
    end

    return words
  end

  private

  def load_title
    @title = document.css('TITLE').map(&:content)[0]
  end

  def load_characters
    @characters = Set.new
    document.css('SPEAKER').map do |character|
      @characters << character.text
    end
  end

  def load_acts
    @acts = document.css('ACT').map do |act_document|
      Act.new act_document
    end
  end

end

app/models/scene.rb
require_relative './speech'

class Scene
  attr_accessor :document, :title, :speeches

  def initialize(document)
    @document = document
    load_title
    load_speeches
  end

  def load_title
    @title = document.css('TITLE').map(&:content)[0]
  end

  def load_speeches
    @speeches = document.css('SPEECH').map do |speech_document|
      Speech.new speech_document
    end
  end

end

app/models/speech.rb
class Speech

  attr_accessor :speaker, :lines

  def initialize( speech_source )
    @speech_source = speech_source
    load_speakers
    load_lines
  end

  def load_speakers
    @speaker = @speech_source.css('SPEAKER').map(&:content)[0]
  end

  def load_lines
    @lines = @speech_source.css('LINE').map(&:content)
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
require "#{Rails.root}/lib/plays_list"

class HomeController < ApplicationController
  def index
    @plays = PlaysList.new.list
  end

end

app/controllers/play_controller.rb
require "#{Rails.root}/lib/plays_list"
require "#{Rails.root}/lib/http_source"

class PlayController < ApplicationController
  def index
    @plays = PlaysList.new.list
    @id = params[:id].to_i
    @http = HttpSource.new(get_source_play(@id))
    @play = Play.new(@http)
  end

  private
    def get_source_play(id)
      @source = @plays[id][0]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<h1>About the interview in LaHaus</h1>
<a href="https://www.lahaus.com/">LaHause</a>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">
  <div class="container-fluid">

    <a class="navbar-brand" href="#">
      <!--<img src="/assets/images/shakespear.png" alt="" width="30" height="24">-->
      <%= image_tag("Shakespeare.jfif", alt: '', width: 30, height: 24) %>
    </a>

    <%= link_to 'Shakespeare Plays', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Us", about_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="row row-cols-1 row-cols-md-4 g-4">
  <% @plays.each_with_index do |play, i| %>
    <div class="col">
    <div class="card h-100">
      <% if i % 2 == 0 %>
        <%= image_tag("images2.png", alt: play[1], class: "card-img-top") %>
      <% else %>
        <%= image_tag("images.png", alt: play[1], class: "card-img-top") %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"></h5>
        <p class="card-text"></p>
      </div>
      <div class="card-footer">
        <small class="text-muted"><%= link_to play[1], play_path(i), class: "link-dark" %></small>
      </div>
    </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  <title>Shakespeare Plays</title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>
<body>

  <%= render 'home/header' %>
  </br>
  </br>
  <div class="container">
    <br/>
    <%= yield %>
  </div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
-->
</body>
</html>

app/views/play/index.html.erb
<h1 class="title"><%= @play.title %></h1>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="acts-tab" data-bs-toggle="tab" data-bs-target="#acts" type="button" role="tab" aria-controls="home" aria-selected="true">Acts</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="characters-tab" data-bs-toggle="tab" data-bs-target="#characters" type="button" role="tab" aria-controls="profile" aria-selected="false">Characters</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="acts" role="tabpanel" aria-labelledby="acts-tab">
    <div class="container">
      </br>
      <div class="accordion" id="accordionExample">
        <% @play.acts.each_with_index do |act, index| %>
          <div class="accordion-item">
            <h2 class="accordion-header" id="<%= 'heading-' + index.to_s %>">
              <button class="accordion-button <%= "collapsed" if index!=0 %>" type="button" data-bs-toggle="collapse"
                      data-bs-target="<%= '#collapse-' + index.to_s %>" aria-expanded="<%= index==0 %>"
                      aria-controls="<%= 'collapse-' + index.to_s %>">
                <%= act.title %>
              </button>
            </h2>
            <div id="<%= 'collapse-' + index.to_s %>" class="accordion-collapse collapse <%= "show" if index==0 %>"
                 aria-labelledby="<%= 'heading' + index.to_s %>" data-bs-parent="#accordionExample">
              <div class="accordion-body">

                <div class="bd-spy">
                  <div class="row">

                    <div class="col-4">
                      <div id="list-example" class="list-group">
                        <% act.scenes.each_with_index do |scene, i| %>
                          <a class="list-group-item list-group-item-action"
                             href="#list-item-<%= index.to_s + '-' + i.to_s %>"><%= scene.title %></a>
                        <% end %>
                      </div>
                    </div>

                    <div class="col-8 overflow-auto" style="max-height: 400px;">
                      <div data-bs-spy="bd-spy" data-bs-target="#list-example" data-bs-offset="0" class="overflow-auto" tabindex="0">
                        <% act.scenes.each_with_index do |scene, i| %>
                          <h4 class="text-center" id="list-item-<%= index.to_s + '-' + i.to_s %>"><%= scene.title %></h4>
                          <% scene.speeches.each do |speech| %>
                            <h6>Speaker: <%= speech.speaker %></h6>
                            <% speech.lines.each do |line| %>
                              <p> * <%= line %></p>
                            <% end %>
                          <% end %>
                        <% end %>
                      </div>
                    </div>

                  </div>
                </div>
              </div>

            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="tab-pane fade" id="characters" role="tabpanel" aria-labelledby="characters-tab">
    </br>
    <div class="container">
      <div class="row row-cols-1 row-cols-md-3 g-4">
        <% @play.characters.each do |character| %>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <%= image_tag("character.jfif", alt: '', class: "card-img-top") %>
              <div class="card-body">
                <h5 class="card-title"><%= character %></h5>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Lines by Character: <%= @play.lines_by_character character %></li>
                <li class="list-group-item">Words by Character: <%= @play.words_by_character(character).size %></li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>